### PR TITLE
A stack of dragged float cards moves together

### PR DESCRIPTION
**Pull request by julien2512**

### CODE REVIEW

**Comment by andydotxyz** [comment]
This is really excellent thanks, but it looks like it introduced a new bug - when you drag the bottom of the 3 items on the revealed pile (after moving the other two) it takes the look of the pile bottom instead of remaining the face of the card:

Screenshot 2024-09-17 at 18 03 10

**Review by andydotxyz — CHANGES_REQUESTED** [review]
Code looks good, but can you look at the new bug noted on the conversation - the bottom of the 3 revealed cards now goes loses its face when dragged.

**Comment by julien2512** [comment]
Thank you for your feed back.
I finally got what the "last" return value was for on the findCard method !

**Review by andydotxyz — APPROVED** [review]
Amazing to have this improvement, thanks so much!

**Pull request merged**
